pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

rootProject.name = 'emerald-tools-justfatlard'

include ':pandorical'
project(':pandorical').projectDir = new File(rootProject.projectDir, '../pandorical')
